// SPDX-License-Identifier: Apache-2.0
//
// The core crate is reached as `::nameparser_core::...`, NOT `::nameparser::...` (contrast
// crates/nameparser-py/src/lib.rs, which uses a bare `nameparser` dependency key with the
// leading `::` alone to disambiguate it from that crate's own `#[pymodule] fn nameparser`).
// Here the `[dependencies]` entry itself is renamed via Cargo's `package =` key — see
// bindings/r/src/rust/Cargo.toml for why: this package also has a `[[bin]] document` target
// (generated by `rextendr::use_extendr()`) that Cargo auto-links against this package's own
// `[lib]` target (also named "nameparser"), so a plain `nameparser = { path = ... }` core
// dependency would give that bin target two different rlibs both bound to the extern name
// `nameparser` — `error[E0464]: multiple candidates for `rlib` dependency `nameparser` found`,
// which (verified) a leading `::` does not fix, unlike lib.rs's own same-name ambiguity.
use extendr_api::prelude::*;

/// Minimal spike: one row per input name, proving Vec<Option<_>> -> NA + tibble wrap.
/// @export
#[extendr]
fn parse_names_impl(scientificname: Vec<String>) -> List {
    let n = scientificname.len();
    let parsed: Vec<Option<bool>> = scientificname
        .iter()
        .map(|s| Some(::nameparser_core::parse(s, None, None, None).is_ok()))
        .collect();
    // A deliberately-NA-bearing column: the message on failure, NA on success.
    let error: Vec<Option<String>> = scientificname
        .iter()
        .map(|s| {
            ::nameparser_core::parse(s, None, None, None)
                .err()
                .map(|e| e.message)
        })
        .collect();
    let names_col: Vec<Option<String>> = scientificname.into_iter().map(Some).collect();
    let _ = n;
    List::from_names_and_values(
        ["scientificName", "parsed", "error"],
        [r!(names_col), r!(parsed), r!(error)],
    )
    .expect("equal-length, well-formed columns")
}

extendr_module! {
    mod nameparser;
    fn parse_names_impl;
}
