// SPDX-License-Identifier: Apache-2.0
//
// The core crate is reached as `::nameparser_core::...`, NOT `::nameparser::...` (contrast
// crates/nameparser-py/src/lib.rs, which uses a bare `nameparser` dependency key with the
// leading `::` alone to disambiguate it from that crate's own `#[pymodule] fn nameparser`).
// Here the `[dependencies]` entry itself is renamed via Cargo's `package =` key — see
// bindings/r/src/rust/Cargo.toml for why: this package also has a `[[bin]] document` target
// (generated by `rextendr::use_extendr()`) that Cargo auto-links against this package's own
// `[lib]` target (also named "nameparser"), so a plain `nameparser = { path = ... }` core
// dependency would give that bin target two different rlibs both bound to the extern name
// `nameparser` — `error[E0464]: multiple candidates for `rlib` dependency `nameparser` found`,
// which (verified) a leading `::` does not fix, unlike lib.rs's own same-name ambiguity.
use extendr_api::prelude::*;
use ::nameparser_core::model::{NomCode, ParsedName, Rank};

/// Render any serde-serializable core value (enums are serde-only, no Display/.name())
/// to its SCREAMING_SNAKE_CASE string; `None`/non-string -> `None` (=> R `NA`).
fn enum_name<T: serde::Serialize>(v: &T) -> Option<String> {
    serde_json::to_value(v).ok().and_then(|j| j.as_str().map(str::to_owned))
}

/// One column-builder closure per output column keeps the parallel Vec<Option<_>>s in lockstep.
struct Cols {
    scientific_name: Vec<Option<String>>,
    parsed: Vec<Option<bool>>,
    error: Vec<Option<String>>,
    r#type: Vec<Option<String>>,
    rank: Vec<Option<String>>,
    code: Vec<Option<String>>,
    uninomial: Vec<Option<String>>,
    genus: Vec<Option<String>>,
    infrageneric_epithet: Vec<Option<String>>,
    specific_epithet: Vec<Option<String>>,
    infraspecific_epithet: Vec<Option<String>>,
    cultivar_epithet: Vec<Option<String>>,
    phrase: Vec<Option<String>>,
    candidatus: Vec<Option<bool>>,
    notho: Vec<Option<String>>,
    original_spelling: Vec<Option<bool>>,
    epithet_qualifier: Vec<Option<String>>,
    extinct: Vec<Option<bool>>,
    taxonomic_note: Vec<Option<String>>,
    nomenclatural_note: Vec<Option<String>>,
    published_in: Vec<Option<String>>,
    published_in_year: Vec<Option<i32>>,
    published_in_page: Vec<Option<String>>,
    unparsed: Vec<Option<String>>,
    doubtful: Vec<Option<bool>>,
    manuscript: Vec<Option<bool>>,
    state: Vec<Option<String>>,
    combination_authors: Vec<Option<String>>,
    combination_ex_authors: Vec<Option<String>>,
    combination_year: Vec<Option<String>>,
    basionym_authors: Vec<Option<String>>,
    basionym_ex_authors: Vec<Option<String>>,
    basionym_year: Vec<Option<String>>,
    sanctioning_author: Vec<Option<String>>,
    warnings: Vec<Option<String>>,
}

/// Join a list of authors to one cell, or `None` (=> NA) when empty.
fn join_authors(a: &[String]) -> Option<String> {
    if a.is_empty() { None } else { Some(a.join(", ")) }
}

impl Cols {
    fn with_capacity(n: usize) -> Self {
        macro_rules! v { () => { Vec::with_capacity(n) }; }
        Cols {
            scientific_name: v!(), parsed: v!(), error: v!(), r#type: v!(), rank: v!(),
            code: v!(), uninomial: v!(), genus: v!(), infrageneric_epithet: v!(),
            specific_epithet: v!(), infraspecific_epithet: v!(), cultivar_epithet: v!(),
            phrase: v!(), candidatus: v!(), notho: v!(), original_spelling: v!(),
            epithet_qualifier: v!(), extinct: v!(), taxonomic_note: v!(),
            nomenclatural_note: v!(), published_in: v!(), published_in_year: v!(),
            published_in_page: v!(), unparsed: v!(), doubtful: v!(), manuscript: v!(),
            state: v!(), combination_authors: v!(), combination_ex_authors: v!(),
            combination_year: v!(), basionym_authors: v!(), basionym_ex_authors: v!(),
            basionym_year: v!(), sanctioning_author: v!(), warnings: v!(),
        }
    }

    fn push_ok(&mut self, input: &str, pn: &ParsedName) {
        self.scientific_name.push(Some(input.to_owned()));
        self.parsed.push(Some(true));
        self.error.push(None);
        self.r#type.push(enum_name(&pn.type_));
        self.rank.push(enum_name(&pn.rank));
        self.code.push(enum_name(&pn.code));
        self.uninomial.push(pn.uninomial.clone());
        self.genus.push(pn.genus.clone());
        self.infrageneric_epithet.push(pn.infrageneric_epithet.clone());
        self.specific_epithet.push(pn.specific_epithet.clone());
        self.infraspecific_epithet.push(pn.infraspecific_epithet.clone());
        self.cultivar_epithet.push(pn.cultivar_epithet.clone());
        self.phrase.push(pn.phrase.clone());
        self.candidatus.push(Some(pn.candidatus));
        self.notho.push(pn.notho.as_ref().map(|parts| {
            parts.iter().filter_map(enum_name).collect::<Vec<_>>().join(", ")
        }));
        self.original_spelling.push(pn.original_spelling);
        self.epithet_qualifier.push(pn.epithet_qualifier.as_ref().map(|m| {
            let mut kv: Vec<String> = m.iter()
                .map(|(k, val)| format!("{}={}", enum_name(k).unwrap_or_default(), val))
                .collect();
            kv.sort();               // deterministic order regardless of map iteration
            kv.join(", ")
        }));
        self.extinct.push(Some(pn.extinct));
        self.taxonomic_note.push(pn.taxonomic_note.clone());
        self.nomenclatural_note.push(pn.nomenclatural_note.clone());
        self.published_in.push(pn.published_in.clone());
        self.published_in_year.push(pn.published_in_year);
        self.published_in_page.push(pn.published_in_page.clone());
        self.unparsed.push(pn.unparsed.clone());
        self.doubtful.push(Some(pn.doubtful));
        self.manuscript.push(Some(pn.manuscript));
        self.state.push(enum_name(&pn.state));
        self.combination_authors.push(join_authors(&pn.combination_authorship.authors));
        self.combination_ex_authors.push(join_authors(&pn.combination_authorship.ex_authors));
        self.combination_year.push(pn.combination_authorship.year.clone());
        self.basionym_authors.push(join_authors(&pn.basionym_authorship.authors));
        self.basionym_ex_authors.push(join_authors(&pn.basionym_authorship.ex_authors));
        self.basionym_year.push(pn.basionym_authorship.year.clone());
        self.sanctioning_author.push(pn.sanctioning_author.clone());
        self.warnings.push(join_authors(&pn.warnings));   // same "join or NA" semantics
    }

    fn push_err(&mut self, input: &str, e: &::nameparser_core::model::ParseError) {
        self.scientific_name.push(Some(input.to_owned()));
        self.parsed.push(Some(false));
        self.error.push(Some(e.message.clone()));
        self.r#type.push(enum_name(&e.type_));
        // no ParsedName exists on error -> every parsed atom/flag is NA
        for col in [
            &mut self.rank, &mut self.code, &mut self.uninomial, &mut self.genus,
            &mut self.infrageneric_epithet, &mut self.specific_epithet,
            &mut self.infraspecific_epithet, &mut self.cultivar_epithet, &mut self.phrase,
            &mut self.notho, &mut self.epithet_qualifier, &mut self.taxonomic_note,
            &mut self.nomenclatural_note, &mut self.published_in, &mut self.published_in_page,
            &mut self.unparsed, &mut self.state,
            &mut self.combination_authors, &mut self.combination_ex_authors,
            &mut self.combination_year, &mut self.basionym_authors,
            &mut self.basionym_ex_authors, &mut self.basionym_year,
            &mut self.sanctioning_author, &mut self.warnings,
        ] {
            col.push(None);
        }
        self.candidatus.push(None);
        self.original_spelling.push(None);
        self.extinct.push(None);
        self.published_in_year.push(None);
        self.doubtful.push(None);
        self.manuscript.push(None);
    }
}

fn hint(o: &Nullable<String>) -> Option<&str> {
    match o {
        Nullable::NotNull(s) => Some(s.as_str()),
        Nullable::Null => None,
    }
}

/// Low-level column-list builder behind the R wrapper `parse_names()` (`bindings/r/R/parse.R`).
/// Not exported — kept package-internal, since it returns a raw named `List` of parallel
/// columns rather than the tibble users should call.
/// @noRd
#[extendr]
fn parse_names_impl(
    scientificname: Vec<String>,
    authorship: Nullable<String>,
    rank: Nullable<String>,
    code: Nullable<String>,
) -> List {
    let rank = hint(&rank).and_then(Rank::from_name);
    let code = hint(&code).and_then(NomCode::from_name);
    let auth = hint(&authorship);
    let mut c = Cols::with_capacity(scientificname.len());
    for name in &scientificname {
        match ::nameparser_core::parse(name, auth, rank, code) {
            Ok(pn) => c.push_ok(name, &pn),
            Err(e) => c.push_err(name, &e),
        }
    }
    List::from_names_and_values(
        [
            "scientificName", "parsed", "error", "type", "rank", "code", "uninomial",
            "genus", "infragenericEpithet", "specificEpithet", "infraspecificEpithet",
            "cultivarEpithet", "phrase", "candidatus", "notho", "originalSpelling",
            "epithetQualifier", "extinct", "taxonomicNote", "nomenclaturalNote",
            "publishedIn", "publishedInYear", "publishedInPage", "unparsed", "doubtful",
            "manuscript", "state", "combinationAuthors", "combinationExAuthors",
            "combinationYear", "basionymAuthors", "basionymExAuthors", "basionymYear",
            "sanctioningAuthor", "warnings",
        ],
        [
            r!(c.scientific_name), r!(c.parsed), r!(c.error), r!(c.r#type), r!(c.rank),
            r!(c.code), r!(c.uninomial), r!(c.genus), r!(c.infrageneric_epithet),
            r!(c.specific_epithet), r!(c.infraspecific_epithet), r!(c.cultivar_epithet),
            r!(c.phrase), r!(c.candidatus), r!(c.notho), r!(c.original_spelling),
            r!(c.epithet_qualifier), r!(c.extinct), r!(c.taxonomic_note),
            r!(c.nomenclatural_note), r!(c.published_in), r!(c.published_in_year),
            r!(c.published_in_page), r!(c.unparsed), r!(c.doubtful), r!(c.manuscript),
            r!(c.state), r!(c.combination_authors), r!(c.combination_ex_authors),
            r!(c.combination_year), r!(c.basionym_authors), r!(c.basionym_ex_authors),
            r!(c.basionym_year), r!(c.sanctioning_author), r!(c.warnings),
        ],
    )
    .expect("all columns are the same length (one push per input name)")
}

/// Builds `{"error":{"type":...,"code":...,"message":...}}` — byte-for-byte the same shape
/// `nameparser-ffi`'s private `unparsable_json` builds (and `nameparser-cli`'s `render_row`
/// writes for its own `"error"` value: `crates/nameparser-ffi/src/lib.rs` lines ~143-166,
/// `crates/nameparser-cli/src/main.rs`'s `render_row`): `code` is OMITTED (not serialized as
/// `null`) when absent, there is no `name` key, and the key order is `type`, `code`,
/// `message` — NOT the alphabetical order a dynamically-built `serde_json::Map` would
/// produce (this crate's `serde_json` dependency has no `preserve_order` feature enabled
/// either, for the same reason the FFI crate hand-assembles instead of using `json!`). Each
/// leaf value is still rendered via `serde_json::to_string`, for correct JSON string escaping.
fn unparsable_json(e: &::nameparser_core::model::ParseError) -> String {
    let mut out = String::with_capacity(96);
    out.push_str("{\"error\":{\"type\":");
    out.push_str(&serde_json::to_string(&e.type_).expect("NameType always serializes to JSON"));
    if let Some(code) = &e.code {
        out.push_str(",\"code\":");
        out.push_str(&serde_json::to_string(code).expect("NomCode always serializes to JSON"));
    }
    out.push_str(",\"message\":");
    out.push_str(
        &serde_json::to_string(&e.message).expect("a String always serializes to a JSON string"),
    );
    out.push_str("}}");
    out
}

/// Lossless escape hatch + parity oracle: the core's own serde JSON for one name
/// (byte-identical to the CLI's `parsed` object), or `{"error":{…}}` on failure.
/// @noRd
#[extendr]
fn parse_name_json_impl(
    name: String,
    authorship: Nullable<String>,
    rank: Nullable<String>,
    code: Nullable<String>,
) -> String {
    let rank = hint(&rank).and_then(Rank::from_name);
    let code = hint(&code).and_then(NomCode::from_name);
    match ::nameparser_core::parse(&name, hint(&authorship), rank, code) {
        Ok(pn) => serde_json::to_string(&pn).unwrap_or_else(|e| format!("{{\"error\":\"{e}\"}}")),
        Err(e) => unparsable_json(&e),
    }
}

extendr_module! {
    mod nameparser;
    fn parse_names_impl;
    fn parse_name_json_impl;
}
