#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Cross-validates the Rust CLI's `parse` output against the Java CLI's, over every corpus in
# testdata/, using the `compare` subcommand (Phase 2 Task 3). For each `testdata/<name>.txt`
# corpus this: (1) runs the Java `name-parser-cli` shaded jar's `parse`, (2) runs this repo's
# `nameparser-cli` release binary's `parse`, (3) diffs the two resulting JSONL files with
# `nameparser-cli compare` and prints the parity summary.
#
# The generated `<name>.java.jsonl` / `<name>.rust.jsonl` files are left in testdata/ for
# inspection (e.g. `less`, or feeding straight back into `nameparser-cli compare --output=...`
# for a full per-row dump) — they are regenerated by every run and are git-ignored, not
# committed (see .gitignore).
#
# Usage:
#   scripts/cross-validate.sh [corpus-name ...]
#
#   With no arguments, runs over the default corpus set this task cross-validated: the 8017-name
#   benchmark corpus plus the 6 Java `name-parser` test-resource corpora
#   (names-with-authors/hybrids/other/otu/placeholder/viruses) copied into testdata/.
#
# Environment:
#   JAR        path to the Java name-parser-cli shaded jar (default: discovered under
#              /Users/markus/code/gbif/name-parser/name-parser-cli/target/)
#   MAX_DIFFS  passed to `nameparser-cli compare --max-diffs` (default 1000 — generous, so a
#              triage run sees every differing row up front rather than needing a re-run)
#
# Requires: a release build of nameparser-cli (`cargo build --release -p nameparser-cli`) and a
# `java` on PATH able to run the shaded jar.

set -euo pipefail
cd "$(dirname "$0")/.."

JAR="${JAR:-$(ls /Users/markus/code/gbif/name-parser/name-parser-cli/target/name-parser-cli-*-shaded.jar 2>/dev/null | head -1)}"
if [ -z "$JAR" ] || [ ! -f "$JAR" ]; then
  echo "Java name-parser-cli shaded jar not found — set \$JAR to its path, or build it first" \
       "(cd .../name-parser/name-parser-cli && mvn -q package)." >&2
  exit 1
fi

RUST_CLI="./target/release/nameparser-cli"
if [ ! -x "$RUST_CLI" ]; then
  echo "Rust CLI not built — run: cargo build --release -p nameparser-cli" >&2
  exit 1
fi

MAX_DIFFS="${MAX_DIFFS:-1000}"

CORPORA=("$@")
if [ ${#CORPORA[@]} -eq 0 ]; then
  CORPORA=(benchmark-data names-with-authors hybrids other otu placeholder viruses)
fi

overall_status=0
for name in "${CORPORA[@]}"; do
  corpus="testdata/${name}.txt"
  if [ ! -f "$corpus" ]; then
    echo "SKIP $name: $corpus not found" >&2
    continue
  fi
  java_out="testdata/${name}.java.jsonl"
  rust_out="testdata/${name}.rust.jsonl"

  java -jar "$JAR" parse --input="$corpus" --output=- --format=jsonl > "$java_out" 2>/dev/null
  "$RUST_CLI" parse --input="$corpus" --output=- --quiet > "$rust_out"

  echo "################################################################################"
  echo "# ${name}  (${corpus})"
  echo "################################################################################"
  "$RUST_CLI" compare "$java_out" "$rust_out" --max-diffs="$MAX_DIFFS" || overall_status=$?
  echo
done

exit "$overall_status"
