#!/usr/bin/env python3
"""Render docs/parsing-examples.md from tools/parsing-examples.txt with the Python binding.

    python tools/parsing_examples.py [source] [target]

Needs the `nameparser` module of this repo installed (see crates/nameparser-py), so the document
shows what the current engine returns. Re-run it after a change in parsing behaviour.
"""

import sys
from pathlib import Path

import nameparser

ROOT = Path(__file__).resolve().parent.parent
SOURCE = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "tools" / "parsing-examples.txt"
TARGET = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "docs" / "parsing-examples.md"

INTRO = """# Parsing examples

How the GBIF name parser reads real scientific names, and what it returns for them. Every example
below was parsed by the current engine; the document is generated by `tools/parsing_examples.py`
from the list in `tools/parsing-examples.txt`.

## The parse result

A name is parsed into one of three results:

- **Parsed** — a `ParsedName`: the name parts (`uninomial`, or `genus`, `infragenericEpithet`,
  `specificEpithet`, `infraspecificEpithet`, `cultivarEpithet`), the `rank`, the nomenclatural
  `code` when there is evidence for it, the `type` (`SCIENTIFIC`, or `INFORMAL` for a name in open
  nomenclature), the authorship, notes and flags. Its `state` is `COMPLETE`, or `PARTIAL` when a
  rest could not be read (`unparsed`).
- **Informal** — a provisional name with no epithet of its own (`Bacillus sp. 1`): the anchor
  `taxon` and its `taxonRank`, the `rank` the designation stands for and the designation itself,
  verbatim, as the `phrase`.
- **Unparsable** — no scientific name at all (a virus, a placeholder, an identifier, a hybrid
  formula): only its `type` and, where known, its `code`.

The authorship of a name is split in two: the **combination** authorship and the **basionym**
authorship, the author of the original name, cited in brackets. Each holds the `authors`, the
`exAuthors` (who proposed a name someone else published), the `year`, an `imprintYear`, the flags
`bracketedYear` and `anonymous`, and in mycology a `sanctioningAuthor`. The author of the species
in an infraspecific name, and the author of the genus in an infrageneric one, are kept apart as
`specificAuthorship` and `genericAuthorship`.

A name can also be given with its authorship in a separate column, as checklists often do; the
examples marked *authorship given separately* are parsed that way, and come out alike.

Below each result is the name rebuilt from its parts (`canonicalComplete`).
"""


def code(value) -> str:
    return "`" + str(value).replace("`", "'").replace("|", "\\|") + "`"


def authorship_line(label: str, a: dict) -> str | None:
    """One authorship (as its `to_dict()`), or None when empty."""
    parts = []
    authors = a.get("authors") or []
    if authors:
        parts.append("authors " + ", ".join(code(x) for x in authors))
    ex = a.get("exAuthors") or []
    if ex:
        parts.append("ex " + ", ".join(code(x) for x in ex))
    if a.get("year"):
        parts.append("year " + code(a["year"]))
    if a.get("bracketedYear"):
        parts.append("bracketedYear")
    if a.get("imprintYear"):
        parts.append("imprintYear " + code(a["imprintYear"]))
    if a.get("anonymous"):
        parts.append("anonymous")
    if a.get("sanctioningAuthor"):
        parts.append("sanctioningAuthor " + code(a["sanctioningAuthor"]))
    return f"{label}: " + " · ".join(parts) if parts else None


def render_parsed(pn) -> list[str]:
    head = ["**Parsed**", code(pn.type), "rank " + code(pn.rank)]
    if pn.code:
        head.append("code " + code(pn.code))
    if pn.state != "COMPLETE":
        head.append("state " + code(pn.state))
    lines = [" · ".join(head)]

    parts = []
    for field, value in [
        ("uninomial", pn.uninomial),
        ("genus", pn.genus),
        ("infragenericEpithet", pn.infrageneric_epithet),
        ("specificEpithet", pn.specific_epithet),
        ("infraspecificEpithet", pn.infraspecific_epithet),
        ("cultivarEpithet", pn.cultivar_epithet),
        ("phrase", pn.phrase),
    ]:
        if value:
            parts.append(f"{field} {code(value)}")
    if parts:
        lines.append(" · ".join(parts))

    flags = []
    if pn.candidatus:
        flags.append("candidatus")
    if pn.notho:
        flags.append("notho " + ", ".join(code(n) for n in pn.notho))
    if pn.epithet_qualifier:
        flags.append(
            "epithetQualifier "
            + ", ".join(f"{code(k)} {code(v)}" for k, v in pn.epithet_qualifier.items())
        )
    if pn.extinct:
        flags.append("extinct")
    if pn.doubtful:
        flags.append("doubtful")
    if pn.manuscript:
        flags.append("manuscript")
    if pn.original_spelling is not None:
        flags.append(f"originalSpelling {code(pn.original_spelling)}")
    if flags:
        lines.append(" · ".join(flags))

    d = pn.to_dict()
    for label, key in [
        ("combination", "combinationAuthorship"),
        ("basionym", "basionymAuthorship"),
    ]:
        line = authorship_line(label, d.get(key) or {})
        if line:
            lines.append(line)
    for label, key in [("specificAuthorship", "specificAuthorship"), ("genericAuthorship", "genericAuthorship")]:
        ca = d.get(key)
        if ca:
            for half, sub in [("combination", "combinationAuthorship"), ("basionym", "basionymAuthorship")]:
                line = authorship_line(f"{label} {half}", ca.get(sub) or {})
                if line:
                    lines.append(line)

    for field, value in [
        ("taxonomicNote", pn.taxonomic_note),
        ("nomenclaturalNote", pn.nomenclatural_note),
        ("publishedIn", pn.published_in),
        ("publishedInYear", pn.published_in_year),
        ("publishedInPage", pn.published_in_page),
        ("unparsed", pn.unparsed),
    ]:
        if value is not None and value != "":
            lines.append(f"{field} {code(value)}")
    if pn.warnings:
        lines.append("warnings " + ", ".join(code(w) for w in pn.warnings))
    canonical = pn.canonical_name_complete()
    if canonical:
        lines.append("→ " + code(canonical))
    return lines


def render_informal(inf) -> list[str]:
    head = [
        "**Informal**",
        "taxon " + code(inf.taxon),
        "taxonRank " + code(inf.taxon_rank),
        "rank " + code(inf.rank),
    ]
    if inf.code:
        head.append("code " + code(inf.code))
    lines = [" · ".join(head)]
    if inf.phrase:
        lines.append("phrase " + code(inf.phrase))
    lines.append("→ " + code(inf.canonical_name()))
    return lines


def render(name: str, authorship: str | None) -> list[str]:
    try:
        result = nameparser.parse(name, authorship=authorship)
    except nameparser.UnparsableNameError as err:
        head = ["**Unparsable**", "type " + code(err.name_type)]
        if err.code:
            head.append("code " + code(err.code))
        return [" · ".join(head)]
    if isinstance(result, nameparser.Informal):
        return render_informal(result)
    return render_parsed(result)


def main() -> None:
    out = [INTRO]
    count = 0
    in_table = False
    for raw in SOURCE.read_text(encoding="utf-8").splitlines():
        if not raw.strip() or (raw.startswith("#") and not raw.startswith("## ")):
            continue
        if raw.startswith("## "):
            out.append(f"\n## {raw[3:].strip()}\n")
            in_table = False
            continue
        if raw.startswith(">"):
            out.append(raw[1:].strip() + "\n")
            continue
        if not in_table:
            out.append("| Name | Parsed as |\n|---|---|")
            in_table = True
        line, _, remark = raw.partition("  # ")
        name, _, authorship = line.partition("\t")
        name, authorship = name.strip(), authorship.strip() or None
        cell = code(name)
        if authorship:
            cell += "<br>authorship given separately: " + code(authorship)
        if remark.strip():
            cell += "<br>*" + remark.strip() + "*"
        out.append(f"| {cell} | {'<br>'.join(render(name, authorship))} |")
        count += 1
    TARGET.write_text("\n".join(out).rstrip("\n") + "\n", encoding="utf-8")
    print(f"{count} examples written to {TARGET}")


if __name__ == "__main__":
    main()
