# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib nameparser, .registration = TRUE
NULL

#' Minimal spike: one row per input name, proving Vec<Option<_>> -> NA + tibble wrap.
#' @export
parse_names_impl <- function(scientificname) .Call(wrap__parse_names_impl, scientificname)

# nolint end
