# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib nameparser, .registration = TRUE
NULL

#' @export
parse_names_impl <- function(scientificname, authorship, rank, code) .Call(wrap__parse_names_impl, scientificname, authorship, rank, code)

# nolint end
